# Generated by Django 4.0.5 on 2022-06-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_apointment_services_alter_apointment_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apointment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Apointment', 'verbose_name_plural': 'Apointments'},
        ),
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Doctor', 'verbose_name_plural': 'Doctors'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['title'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AddField(
            model_name='apointment',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
